stages:
  prepare:
    cmd: > 
      python -u scripts/download_wikics.py 
    deps:
      - scripts/download_wikics.py
    outs:
      - data/WikiCS/processed/data_undirected.pt
      - data/WikiCS/processed/pre_filter.pt
      - data/WikiCS/processed/pre_transform.pt
      - data/WikiCS/raw/data.json
  train:
    foreach: ${wikics.train_stage}
    do:
      cmd: > 
        python -u scripts/train_gca_base.py 
        --config
        ${key}
      deps:
        - scripts/train_gca_base.py
        - data/WikiCS/processed/data_undirected.pt
        - data/WikiCS/processed/pre_filter.pt
        - data/WikiCS/processed/pre_transform.pt
        - data/WikiCS/raw/data.json
      params:
        - wikics.train_stage.${key}
      outs:
        - models/gca_${item.encoder}_${item.output_dim}_${item.version}.pt:
            cache: false
  embed:
    foreach: ${wikics.embed_stage}
    do:
      cmd: > 
        python -u scripts/produce_embedings_gca_base.py 
        --config ${key}
      deps:
        - scripts/produce_embedings_gca_base.py
        - models/gca_${item.encoder}_${item.output_dim}_${item.version}.pt
        - data/WikiCS/processed/data_undirected.pt
        - data/WikiCS/processed/pre_filter.pt
        - data/WikiCS/processed/pre_transform.pt
        - data/WikiCS/raw/data.json
      params:
        - wikics.embed_stage.${key}
      outs:
        - data/embeddings/node_embeddings_gca_${item.encoder}_${item.output_dim}_${item.version}.pt:
            cache: false