wikics:
  train_stage:
    train_stage_model_0:
      encoder: gate
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 128
      version: 1.0
    train_stage_model_1:
      encoder: gate
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 256
      version: 1.0
    train_stage_model_2:
      encoder: gate
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 64
      version: 1.0
    train_stage_model_3:
      encoder: gcn
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 128
      version: 1.0
    train_stage_model_4:
      encoder: gcn
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 256
      version: 1.0
    train_stage_model_5:
      encoder: gcn
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 64
      version: 1.0
    train_stage_model_6:
      encoder: gate
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 16
      version: 1.0
    train_stage_model_7:
      encoder: gcn
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 16
      version: 1.0
    train_stage_model_8:
      encoder: gate
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 4
      version: 1.0
    train_stage_model_9:
      encoder: gcn
      lr: 0.01
      weight_decay: 5e-4
      max_epochs: 200
      input_dim: 300
      hidden_dim: 256
      output_dim: 4
      version: 1.0
  embed_stage:
    embed_stage_model_0:
      encoder: gate
      input_dim: 300
      hidden_dim: 256
      output_dim: 128
      version: 1.0
    embed_stage_model_1:
      encoder: gate
      input_dim: 300
      hidden_dim: 256
      output_dim: 256
      version: 1.0
    embed_stage_model_2:
      encoder: gate
      input_dim: 300
      hidden_dim: 256
      output_dim: 64
      version: 1.0
    embed_stage_model_3:
      encoder: gcn
      input_dim: 300
      hidden_dim: 256
      output_dim: 128
      version: 1.0
    embed_stage_model_4:
      encoder: gcn
      input_dim: 300
      hidden_dim: 256
      output_dim: 256
      version: 1.0
    embed_stage_model_5:
      encoder: gcn
      input_dim: 300
      hidden_dim: 256
      output_dim: 64
      version: 1.0
    embed_stage_model_6:
      encoder: gate
      input_dim: 300
      hidden_dim: 256
      output_dim: 16
      version: 1.0
    embed_stage_model_7:
      encoder: gcn
      input_dim: 300
      hidden_dim: 256
      output_dim: 16
      version: 1.0
    embed_stage_model_8:
      encoder: gate
      input_dim: 300
      hidden_dim: 256
      output_dim: 4
      version: 1.0
    embed_stage_model_9:
      encoder: gcn
      input_dim: 300
      hidden_dim: 256
      output_dim: 4
      version: 1.0
  fit_gmm_stage:
    fit_gmm_stage_model_0:
      model: diy
      input_type: embeddings
      input: data/embeddings/node_embeddings_gca_gate_4_1.0.pt
      encoder: gate
      dim: 4
      seed: 13
      tol: 1e-8
      max_epochs: 50
      version: 1.0

